--1.請列出每個借閱人每年借書數量，並依借閱人編號和年度做排序 (Table：BOOK_LEND_RECORD、MEMBER_M)

SELECT  A.USER_ID AS KeeperId, A.USER_CNAME AS CName, A.USER_ENAME AS EName, 
	    YEAR(LEND_DATE) AS BorrowYear, COUNT(BOOK_ID) AS BorrowCnt
FROM MEMBER_M A 
	LEFT JOIN  BOOK_LEND_RECORD B 
		ON A.USER_ID = B. KEEPER_ID 
GROUP BY A.USER_ID, A.USER_CNAME, A.USER_ENAME, YEAR(B.LEND_DATE) 
ORDER BY KeeperId, BorrowYear

--2. 列出最受歡迎的書前五名(借閱數量最多前五名) (Table：BOOK_LEND_RECORD)

--解法一
SELECT TOP(5) WITH TIES A.BOOK_ID, B.BOOK_NAME, COUNT(A.BOOK_ID) AS QTY 
FROM BOOK_LEND_RECORD A 
	INNER JOIN BOOK_DATA B 
		ON A.BOOK_ID = B.BOOK_ID
GROUP BY A.BOOK_ID, B.BOOK_NAME
ORDER BY QTY DESC

--解法二
SELECT T.BOOK_ID, T.BOOK_NAME, T.QTY
FROM (
		SELECT A.BOOK_ID, B.BOOK_NAME, COUNT(A.BOOK_ID) AS QTY, RANK() OVER(ORDER BY COUNT(A.BOOK_ID) DESC) AS [RANK]
		FROM BOOK_LEND_RECORD A 
			INNER JOIN BOOK_DATA B 
				ON A.BOOK_ID = B.BOOK_ID 
		GROUP BY A.BOOK_ID, B.BOOK_NAME
	 ) T 
WHERE [RANK]<=5

--3. 以一季列出2019年每一季書籍借閱書量 (Table：BOOK_LEND_RECORD)

--解法一
SELECT B.SPAN_YEAR + '/' + B.SPAN_START + '~' + B.SPAN_YEAR + '/' + B.SPAN_END AS [Quarter], COUNT(A.BOOK_ID) AS Cnt
FROM BOOK_LEND_RECORD A 
	INNER JOIN SPAN_TABLE B
		ON YEAR(A.LEND_DATE) = B.SPAN_YEAR AND MONTH(A.LEND_DATE) BETWEEN B.SPAN_START AND B.SPAN_END
WHERE YEAR(A.LEND_DATE) = 2019 
GROUP BY SPAN_YEAR, SPAN_START, SPAN_END

--解法二
SELECT CASE WHEN MONTH(LEND_DATE) BETWEEN 1 AND 3 THEN '2019/01~2019/03' 
			WHEN MONTH(LEND_DATE) BETWEEN 4 AND 6 THEN '2019/04~2019/06'
			WHEN MONTH(LEND_DATE) BETWEEN 7 AND 9 THEN '2019/07~2019/09' 
			WHEN MONTH(LEND_DATE) BETWEEN 10 AND 12 THEN '2019/10~2019/12' END AS [Quarter]  
INTO #tmpQuarter
FROM BOOK_LEND_RECORD
WHERE YEAR(LEND_DATE) = 2019

--DROP TABLE #tmpQuarter
--SELECT * FROM #tmpQuarter

SELECT [Quarter], COUNT([Quarter]) AS Cnt
FROM #tmpQuarter
GROUP BY [Quarter]

--解法三
SELECT [Quarter], COUNT([Quarter]) AS Cnt
FROM(
		SELECT CASE WHEN MONTH(LEND_DATE) BETWEEN 1 AND 3 THEN '2019/01~2019/03' 
					WHEN MONTH(LEND_DATE) BETWEEN 4 AND 6 THEN '2019/04~2019/06'
					WHEN MONTH(LEND_DATE) BETWEEN 7 AND 9 THEN '2019/07~2019/09' 
					WHEN MONTH(LEND_DATE) BETWEEN 10 AND 12 THEN '2019/10~2019/12' END AS [Quarter]  
		FROM BOOK_LEND_RECORD
		WHERE YEAR(LEND_DATE) = 2019
) P
GROUP BY [Quarter]

--4. 撈出每個分類借閱數量前三名書本及數量 (Table：BOOK_LEND_RECORD、BOOK_CLASS)

SELECT *
FROM (
		SELECT ROW_NUMBER() OVER(PARTITION BY BOOK_CLASS_NAME ORDER BY COUNT(A.BOOK_ID) DESC) AS Seq, C.BOOK_CLASS_NAME, 
			   A.BOOK_ID, B.BOOK_NAME, COUNT(A.BOOK_ID) AS Cnt
		FROM BOOK_LEND_RECORD A 
			INNER JOIN BOOK_DATA B 
				ON A.BOOK_ID = B.BOOK_ID
			INNER JOIN BOOK_CLASS C 
				ON B.BOOK_CLASS_ID = C.BOOK_CLASS_ID
		GROUP BY C.BOOK_CLASS_NAME, A.BOOK_ID, B.BOOK_NAME
	 ) A 
WHERE A.Seq <= 3

--5. 請列出 2016, 2017, 2018, 2019 各書籍類別的借閱數量比較

--解法一
SELECT B.BOOK_CLASS_ID AS ClassID, C.BOOK_CLASS_NAME AS ClassName,
	   COUNT(CASE WHEN YEAR(A.LEND_DATE) = 2016 THEN 1 ELSE NULL END) AS CNT2016,
	   COUNT(CASE WHEN YEAR(A.LEND_DATE) = 2017 THEN 1 ELSE NULL END) AS CNT2017,
	   COUNT(CASE WHEN YEAR(A.LEND_DATE) = 2018 THEN 1 ELSE NULL END) AS CNT2018,
	   COUNT(CASE WHEN YEAR(A.LEND_DATE) = 2019 THEN 1 ELSE NULL END) AS CNT2019   
FROM BOOK_LEND_RECORD A 
		INNER JOIN BOOK_DATA B 
			ON A.BOOK_ID = B.BOOK_ID
		INNER JOIN BOOK_CLASS C 
			ON B.BOOK_CLASS_ID = C.BOOK_CLASS_ID
GROUP BY B.BOOK_CLASS_ID, C.BOOK_CLASS_NAME
ORDER BY B.BOOK_CLASS_ID

--解法二
SELECT B.BOOK_CLASS_ID AS ClassID, C.BOOK_CLASS_NAME AS ClassName,
	   SUM(CASE WHEN YEAR(A.LEND_DATE) = 2016 THEN 1 ELSE 0 END) AS CNT2016,
	   SUM(CASE WHEN YEAR(A.LEND_DATE) = 2017 THEN 1 ELSE 0 END) AS CNT2017,
	   SUM(CASE WHEN YEAR(A.LEND_DATE) = 2018 THEN 1 ELSE 0 END) AS CNT2018,
	   SUM(CASE WHEN YEAR(A.LEND_DATE) = 2019 THEN 1 ELSE 0 END) AS CNT2019   
FROM BOOK_LEND_RECORD A 
		INNER JOIN BOOK_DATA B 
			ON A.BOOK_ID = B.BOOK_ID
		INNER JOIN BOOK_CLASS C 
			ON B.BOOK_CLASS_ID = C.BOOK_CLASS_ID
GROUP BY B.BOOK_CLASS_ID, C.BOOK_CLASS_NAME
ORDER BY B.BOOK_CLASS_ID

--6. 請使用 PIVOT 語法列出2016, 2017, 2018, 2019 各書籍類別的借閱數量比較

SELECT P.BOOK_CLASS_ID AS ClassID, P.BOOK_CLASS_NAME AS ClassName, ISNULL(P.[2016],0) AS CNT2016, ISNULL(P.[2017],0) AS CNT2017, 
	   ISNULL(P.[2018],0) AS CNT2018, ISNULL(P.[2019],0) AS CNT2019 
FROM (
		SELECT B.BOOK_CLASS_ID, C.BOOK_CLASS_NAME, YEAR(A.LEND_DATE) AS DATE_YEAR, COUNT(A.BOOK_ID) AS Cnt
		FROM BOOK_LEND_RECORD A 
				INNER JOIN BOOK_DATA B 
					ON A.BOOK_ID = B.BOOK_ID
				INNER JOIN BOOK_CLASS C 
					ON B.BOOK_CLASS_ID = C.BOOK_CLASS_ID
		GROUP BY B.BOOK_CLASS_ID, C.BOOK_CLASS_NAME, YEAR(A.LEND_DATE)
) T
PIVOT (
		MAX(Cnt)
		FOR DATE_YEAR IN ([2016],[2017],[2018],[2019])
) P
ORDER BY P.BOOK_CLASS_ID

--7. 請查詢出李四的借書紀錄，其中包含書本ID、購書日期(yyyy/mm/dd)、借閱日期(yyyy/mm/dd)、書籍類別(id-name)、借閱人(id-cname(ename))、狀態(id-name)、購書金額

SELECT A.BOOK_ID AS 書本ID, CONVERT(VARCHAR(10), B.BOOK_BOUGHT_DATE,111) AS 購書日期, 
	   CONVERT(VARCHAR(10), A.LEND_DATE,111) AS 借閱日期, 
	   C.BOOK_CLASS_ID + '-' + C.BOOK_CLASS_NAME AS 書籍類別, 
	   D.USER_ID + '-' + D.USER_CNAME + '(' + D.USER_ENAME + ')' AS 借閱人, 
	   B.BOOK_STATUS + '-' + E.CODE_NAME AS 狀態, 
	   REPLACE(CONVERT(VARCHAR(10), CONVERT(MONEY, B.BOOK_AMOUNT),1),'.00','') +'元' AS 購書金額
FROM MEMBER_M D  
	INNER JOIN BOOK_LEND_RECORD A 
		ON A.KEEPER_ID = D.USER_ID
	INNER JOIN BOOK_DATA B 
		ON A.BOOK_ID = B.BOOK_ID
	INNER JOIN BOOK_CLASS C 
		ON B.BOOK_CLASS_ID = C.BOOK_CLASS_ID
	INNER JOIN BOOK_CODE E 
		ON B.BOOK_STATUS = E.CODE_ID AND E.CODE_TYPE = 'BOOK_STATUS'
WHERE D.USER_ID = '0002'
ORDER BY A.BOOK_ID DESC

--8. 新增一筆借閱紀錄，借書人為李四，書本ID為2004，並修改借閱日期為2019/01/02

BEGIN TRY
	BEGIN TRANSACTION

		INSERT INTO BOOK_LEND_RECORD (BOOK_ID, KEEPER_ID, LEND_DATE, CRE_DATE, CRE_USR, MOD_DATE, MOD_USR)
		SELECT BOOK_ID, '0002' AS KEEPER_ID, '2019/07/15' AS LEND_DATE, GETDATE() AS CRE_DATE, '0002' AS CRE_USR, 
			   GETDATE() AS MOD_DATE, '0002' AS MOD_USR
		FROM BOOK_DATA
		WHERE BOOK_ID = 2004   
		
		UPDATE BOOK_LEND_RECORD 
		SET LEND_DATE = '2019/01/02'
		WHERE BOOK_ID = 2004 AND KEEPER_ID = '0002'

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	SELECT ERROR_NUMBER()
	ROLLBACK TRANSACTION
END CATCH;

SELECT A.BOOK_ID AS 書本ID, CONVERT(VARCHAR, B.BOOK_BOUGHT_DATE,111) AS 購書日期, 
	   CONVERT(VARCHAR, A.LEND_DATE,111) AS 借閱日期, 
	   C.BOOK_CLASS_ID + '-' + C.BOOK_CLASS_NAME AS 書籍類別, 
	   D.USER_ID + '-' + D.USER_CNAME + '(' + D.USER_ENAME + ')' AS 借閱人, 
	   B.BOOK_STATUS + '-' + E.CODE_NAME AS 狀態, 
	   REPLACE(CONVERT(VARCHAR, CONVERT(MONEY, B.BOOK_AMOUNT),1),'.00','') +'元' AS 購書金額
FROM MEMBER_M D  
	INNER JOIN BOOK_LEND_RECORD A 
		ON A.KEEPER_ID = D.USER_ID
	INNER JOIN BOOK_DATA B 
		ON A.BOOK_ID = B.BOOK_ID
	INNER JOIN BOOK_CLASS C 
		ON B.BOOK_CLASS_ID = C.BOOK_CLASS_ID
	INNER JOIN BOOK_CODE E 
		ON B.BOOK_STATUS = E.CODE_ID AND E.CODE_TYPE = 'BOOK_STATUS'
WHERE D.USER_ID = '0002' --AND A.BOOK_ID = '2004'
ORDER BY A.BOOK_ID DESC

--9. 請將題8新增的借閱紀錄(書本ID=2004)刪除

BEGIN TRY
	BEGIN TRAN
		
		DELETE FROM BOOK_LEND_RECORD WHERE
		BOOK_ID = 2004 AND KEEPER_ID = '0002'

	COMMIT TRAN
END TRY
BEGIN CATCH
	SELECT ERROR_NUMBER()
	ROLLBACK TRAN
END CATCH;

SELECT A.BOOK_ID AS 書本ID, CONVERT(VARCHAR, B.BOOK_BOUGHT_DATE,111) AS 購書日期, 
	   CONVERT(VARCHAR, A.LEND_DATE,111) AS 借閱日期, 
	   C.BOOK_CLASS_ID + '-' + C.BOOK_CLASS_NAME AS 書籍類別, 
	   D.USER_ID + '-' + D.USER_CNAME + '(' + D.USER_ENAME + ')' AS 借閱人, 
	   B.BOOK_STATUS + '-' + E.CODE_NAME AS 狀態, 
	   REPLACE(CONVERT(VARCHAR, CONVERT(MONEY, B.BOOK_AMOUNT),1),'.00','') +'元' AS 購書金額
FROM MEMBER_M D  
	INNER JOIN BOOK_LEND_RECORD A 
		ON A.KEEPER_ID = D.USER_ID
	INNER JOIN BOOK_DATA B 
		ON A.BOOK_ID = B.BOOK_ID
	INNER JOIN BOOK_CLASS C 
		ON B.BOOK_CLASS_ID = C.BOOK_CLASS_ID
	INNER JOIN BOOK_CODE E 
		ON B.BOOK_STATUS = E.CODE_ID AND E.CODE_TYPE = 'BOOK_STATUS'
WHERE D.USER_ID = '0002' --AND A.BOOK_ID = '2004'
ORDER BY A.BOOK_ID DESC
