--1.	請列出每個借閱人每年借書數量，並依借閱人編號和年度做排序
SELECT blr.KEEPER_ID AS KeeperId,mm.USER_CNAME AS CName,mm.USER_ENAME AS Ename,
		YEAR(blr.LEND_DATE)AS BorrowYear,COUNT(YEAR(blr.LEND_DATE)) AS BorrowCnt
FROM BOOK_LEND_RECORD blr,MEMBER_M mm
WHERE blr.KEEPER_ID=mm.USER_ID
GROUP BY blr.KEEPER_ID,mm.USER_CNAME,mm.USER_ENAME,YEAR(blr.LEND_DATE)
ORDER BY blr.KEEPER_ID,BorrowYear

--2.	列出最受歡迎的書前五名(借閱數量最多前五名)
SELECT TOP (5)blr.BOOK_ID AS BookId,bd.BOOK_NAME AS BookName,COUNT(blr.BOOK_ID) AS QTY
FROM BOOK_LEND_RECORD blr,BOOK_DATA bd
WHERE bd.BOOK_ID=blr.BOOK_ID
GROUP BY blr.BOOK_ID,bd.BOOK_NAME
ORDER BY Qty DESC

--3.	以一季列出2019年每一季書籍借閱書量
SELECT 
CASE 
	WHEN LEND_DATE>= '2019-01-01' AND LEND_DATE<= '2019-03-31' THEN '2019/01~2019/03'
	WHEN LEND_DATE>='2019-04-01' AND  LEND_DATE <='2019-06-30' THEN '2019/04~2019/06'
	WHEN LEND_DATE>='2019-07-01' AND  LEND_DATE <='2019-09-30' THEN '2019/07~2019/09'
	WHEN LEND_DATE>='2019-10-01' AND  LEND_DATE <='2019-12-31' THEN '2019/10~2019/12'
	END AS Quater,COUNT(BOOK_ID) AS Cnt
FROM BOOK_LEND_RECORD 
WHERE YEAR(LEND_DATE)='2019'
GROUP BY 
	CASE 
	WHEN LEND_DATE>= '2019-01-01' AND LEND_DATE<= '2019-03-31' THEN '2019/01~2019/03'
	WHEN LEND_DATE>='2019-04-01' AND  LEND_DATE <='2019-06-30' THEN '2019/04~2019/06'
	WHEN LEND_DATE>='2019-07-01' AND  LEND_DATE <='2019-09-30' THEN '2019/07~2019/09'
	WHEN LEND_DATE>='2019-10-01' AND  LEND_DATE <='2019-12-31' THEN '2019/10~2019/12'
	 END

--4.	撈出每個分類借閱數量前三名書本及數量
CREATE VIEW count_book
AS 
SELECT bc.BOOK_CLASS_NAME AS BookClass,bd.BOOK_ID AS BookId,
		bd.BOOK_NAME AS BookName,COUNT(bd.BOOK_ID)AS Cnt
FROM BOOK_LEND_RECORD blr,BOOK_DATA bd,BOOK_CLASS bc
WHERE bd.BOOK_ID=blr.BOOK_ID
AND bd.BOOK_CLASS_ID=bc.BOOK_CLASS_ID
GROUP BY bc.BOOK_CLASS_NAME,bd.BOOK_ID,bd.BOOK_NAME

SELECT *
FROM (SELECT ROW_NUMBER() OVER(PARTITION BY  cb.BookClass ORDER BY cb.Cnt DESC,cb.BookId)AS Seq,*
		FROM count_book cb  )AS a
WHERE a.Seq<=3

DROP VIEW count_book

--5.	請列出 2016, 2017, 2018, 2019 各書籍類別的借閱數量比較
;WITH Lend_record
AS (
SELECT YEAR(blr.LEND_DATE) AS [Year],bc.BOOK_CLASS_ID AS BookId,
	bc.BOOK_CLASS_NAME AS ClassName,COUNT(bc.BOOK_CLASS_ID) AS Cnt
FROM BOOK_CLASS bc,BOOK_DATA bd,BOOK_LEND_RECORD blr
WHERE bc.BOOK_CLASS_ID=bd.BOOK_CLASS_ID
AND bd.BOOK_ID=blr.BOOK_ID
GROUP BY YEAR(blr.LEND_DATE),bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME
) 
SELECT BookId,ClassName,
SUM (case [Year] when '2016' then Cnt else 0 END ) as 'CNT2016',
SUM (case [Year] when '2017'then Cnt else 0 end )as 'CNT2017',
SUM (case [Year] when '2018' then Cnt else 0 end )as 'CNT2018',
SUM (case [Year] when '2019' then Cnt else 0 end )as 'CNT2019'
FROM Lend_record
GROUP BY BookId,ClassName
ORDER BY BookId,ClassName;

--6.	請使用 PIVOT 語法列出2016, 2017, 2018, 2019 各書籍類別的借閱數量比較
SELECT BOOK_CLASS_ID AS [ClassId],BOOK_CLASS_NAME AS [ClassName],[2016] AS [CNT2016],
		[2017] AS [CNT2017],[2018] AS [CNT2018],[2019] AS [CNT2019]
FROM (SELECT bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,bd.BOOK_ID,YEAR(blr.LEND_DATE) AS [YEAR]
		FROM BOOK_CLASS bc,BOOK_DATA bd,BOOK_LEND_RECORD blr
		WHERE bc.BOOK_CLASS_ID=bd.BOOK_CLASS_ID
				AND bd.BOOK_ID=blr.BOOK_ID
		 ) AS d
PIVOT(COUNT(d.BOOK_ID) FOR d.[YEAR]
		IN ([2016],[2017],[2018],[2019])) AS pvt
ORDER BY BOOK_CLASS_ID,BOOK_CLASS_NAME

--7.	請查詢出李四的借書紀錄，其中包含書本ID、購書日期(yyyy/mm/dd)、借閱日期(yyyy/mm/dd)、
--		書籍類別(id-name)、借閱人(id-cname(ename))、狀態(id-name)、購書金額
SELECT bd.BOOK_ID AS [書本ID],CONVERT (VARCHAR,bd.BOOK_BOUGHT_DATE,111)AS [購書日期],
		CONVERT (VARCHAR,blr.LEND_DATE,111) AS [借閱日期],(bc.BOOK_CLASS_ID+'-'+bc.BOOK_CLASS_NAME)AS [書籍類別],
		(mm.USER_ID+'-'+mm.USER_CNAME+'('+mm.USER_ENAME+')') AS [借閱人],(bd.BOOK_STATUS+'-'+bc1.CODE_NAME) AS [狀態],
		bd.BOOK_AMOUNT AS [購書金額]
FROM BOOK_CLASS bc,BOOK_CODE bc1,BOOK_DATA bd,BOOK_LEND_RECORD blr,MEMBER_M mm
WHERE bc.BOOK_CLASS_ID=bd.BOOK_CLASS_ID
AND bd.BOOK_ID=blr.BOOK_ID
AND bc1.CODE_ID=bd.BOOK_STATUS
--AND BD.BOOK_KEEPER=MM.USER_ID
AND blr.KEEPER_ID=mm.USER_ID
AND mm.USER_CNAME='李四'
ORDER BY [書本ID]DESC,[購書金額] DESC;

--8.	新增一筆借閱紀錄，借書人為李四，書本ID為2004，並修改借閱日期為2019/01/02
INSERT INTO BOOK_LEND_RECORD([BOOK_ID],[KEEPER_ID],[LEND_DATE]) VALUES ('2004','0002','2019/01/02')

UPDATE BOOK_LEND_RECORD
SET LEND_DATE='2019/01/02'
WHERE KEEPER_ID='0002'

--9.	請將題8新增的借閱紀錄(書本ID=2004)刪除
DELETE BOOK_LEND_RECORD
WHERE BOOK_ID='2004' AND KEEPER_ID='0002'
